version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_CHAT
      TZ: "Asia/Tokyo"
    volumes:
      - ../TEST-CHAT-DB:/var/lib/postgresql/data
  password-challenger:
    build: .
    tty: true
    volumes:
      - ../password-challenger:/app
    depends_on:
      - app